version: '3'
services:
  jekyll:
    build: .
    volumes:
      - .:/site
    ports:
      - "4000:4000"
      - "35729:35729"
    command: bundle exec jekyll serve --host 0.0.0.0 --watch --force_polling --livereload